### ISSUE TITLE
The com.google.android.gms.wearable.BIND_LISTENER action is deprecated. 

### ISSUE THREAD

**Issue by ellis2323** [googlesamples/android-WclDemoSample#1]
When i try to compile this project with Google Play Services 8.4.0, i have this bug. It seems that it is deprecated. This line refers to the AndroidManifest.xml file.

**Comment by IgorGanapolsky** [comment]
Is there an alternative to using **BIND_LISTENER**?  What other intent filters can we use here instead.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
